apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: gcr.io/snowcloud-01/static-web/frontend
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
      timezone: Local
  googleCloudBuild:
    projectId: snowcloud-01
manifests:
  rawYaml:
    - k8s/20-service.yaml
    - k8s/30-deployment.yaml
deploy:
  kubectl: {}
