apiVersion: v1
kind: Service
metadata:
  name: static-web-frontend
  namespace: web
  labels:
    app: "static-web"
    component: frontend
    tier: production
spec:
  ports:
    - port: 8080
      name: http-web
      protocol: TCP
      targetPort: 8080
  selector:
    app: static-web
    component: frontend
    tier: production
  sessionAffinity: None # or ClientIP
  type: ClusterIP
